### ISSUE TITLE
Accessing SSO settings requires logging into mozillians.mozilla.org

### ISSUE THREAD

**Issue by deadsquid** [mozilla-iam/sso-dashboard#102]
This surprised me, given that this is a single sign on portal. Main issue is that "settings" just takes you to your Mozillians profile, and you're forced to auth against mozillians even though you have a valid SSO session.

Steps to reproduce:

1. Authenticate against SSO
2. Select "Settings" from the profile dropdown in the upper right

Expected behaviour: take me to the settings page, ideally so I can see what settings I can tweak (ideally the order of apps on my page ;) ).

Actual behaviour: take me to mozillians.mozilla.org to authenticate, which takes me back to SSO, then takes me to my Mozillians profile, which doesn't have any SSO settings on it near as I can tell.

**Comment by andrewkrug** [comment]
@deadsquid thanks for your report.  Currently the sso-dashboard has no user state  (customization is a future feature).  Everything is asserted from auth0 to build the application grid.  It is our intention that the "settings" gear should take you to your Mozillian's profile since that will soon become home to all attributes about you and your identity at Mozilla.  

Thanks for bringing up the session issue between this app and Mozillian's.  I'll report it to the Mozillian's team.
