### ISSUE TITLE
Suggestions on sso dashboard alerts 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard#230]
1. When getting the alert "Did you recently login from", we should also show to the user the "Yes" button (option), and pressing that button should dismiss the alert. The other options can be "No, Escalate this to security" and "More info", that takes the user to notification page.

2. Make the alert "Your version of Firefox is older than the current stable release." of "Low Risk", with no "Escalate to security" option.

3. On phone (iPhone7), one alert is covering my entire screen. I need to scroll down in order to see to the apps. I would suggest to reduce the size of the alert. @m-branson , any thoughts on this?
![photo_2018-02-23_17-14-59](https://user-images.githubusercontent.com/5293100/36601429-c51c04d2-18bd-11e8-8c03-c9b168a76a0c.jpg)

**Comment by m-branson** [comment]
@viorelaioia thanks for the ping, here are thoughts on each:

>When getting the alert "Did you recently login from", we should also show to the user the "Yes" button (option), and pressing that button should dismiss the alert. The other options can be "No, Escalate this to security" and "More info", that takes the user to notification page.

Agreed that we need a `dismiss` option here. I was under the impression this would be available to users. @andrewkrug remind me, are we able to re-word options; e.g. in this instance `dismiss` could read as `yes`? or do we instead need to add options to the alerts that can be enabled/disabled?

>Make the alert "Your version of Firefox is older than the current stable release." of "Low Risk", with no "Escalate to security" option.

This is purely an infosec call.

>On phone (iPhone7), one alert is covering my entire screen. I need to scroll down in order to see to the apps. I would suggest to reduce the size of the alert. @m-branson , any thoughts on this?

The size of this alert is large on mobile (and desktop) by design. The point of this alert model is to provide an alert option with more feedback per the 'culture of experiments' request @andrewkrug and I fielded from @tristanweir late last year. We have a smaller version of this alert as well that instead pushes users to the notification center to take action. @andrewkrug are there still plans to A/B test these?

@viorelaioia in the short term I recommend we leave the alert layout as it is. We need to understand users feedback and if that feedback is "this is too big, I'm annoyed" -- great, we'll use that data to make an educated decision and implement the smaller solution long term.

**Comment by tristanweir** [comment]
>> Make the alert "Your version of Firefox is older than the current stable release." of "Low Risk", with no "Escalate to security" option.

> This is purely an infosec call.

I agree, there is no action for us to take if the user is using an old browser. It should be for notification only.

**Comment by andrewkrug** [comment]
We did this.  Yay.
