### ISSUE TITLE
UI: search

### ISSUE THREAD

**Issue by jeffbryner** [mozilla-iam/sso-dashboard#36]
Search box for an app is great. It'd be nifty if there was an easy one-click 'clear' search.

Hitting enter in the search tends to clear the search and return to no search which may be counter to expectations.

**Comment by comzeradd** [comment]
I think that's "fixed" with the new UI work. Hitting 'enter' doesn't clear the search anymore. @andrewkrug can you confirm?

**Comment by m-branson** [comment]
Enter doesn't seem to clear the search any longer, though a user does have to fully delete their entry in order to clear the search. I propose that we add an 'x' when the search field is active, allowing the user to fully clear the field with a click (as well as entry delete).

Some proposed updates:

- [ ] Add the 'x' icon to the search active state. [SVG here](https://drive.google.com/a/mozilla.com/file/d/0B0vmiicLLrGud1czemw2NDcwVU0/view?usp=sharing).
- [ ] Add an orange hover state for the 'x' clearing icon.
- [ ] When a user has clicked into (focused) the search field, left-align the cursor to mirror natural english language typing.
- [ ] On desktop viewports, add a hover/rollover state that mirrors the active state (orange outlines)
- [ ] Looks like the text is currently not quite center aligned within the field, @comzeradd can we update this?
- [ ] Increase height of the search container to 40px. (this relates to other sizing updates in [#51)](https://github.com/mozilla-iam/sso-dashboard/issues/51)

![sso-dashboard-search-active](https://cloud.githubusercontent.com/assets/18686986/25354480/efa86216-28e7-11e7-8c78-f9e75b1209ba.png)

**Comment by m-branson** [comment]
@comzeradd assigning this to you as it relates to the issues @viorelaioia noted in #48.
