### ISSUE TITLE
[URGENT] SSO is broken for our CPG Reporting Tool (Convercent)

### ISSUE THREAD

**Issue by LucyeoH** [mozilla-iam/sso-dashboard#392]
Our CPG reporting system for contributors is Convercent. 

When I go to app.convercent.com and try and login, and I start adding my password it starts re-directing me to the Mozilla SSO login page but then drops me back at the convercent login page.

I can see that a report has been submitted to Convercent but can't login to triage it.

**Comment by emmairwin** [comment]
Only people with accounts in the system can login via SSO, two of those people are Lucy and Myself.   We create accounts manually and assign login method as SSO.

I used to see Convercent in my SSO.mozilla.org list as well, and that it is missing makes me feel th issue is at least partially on our side

I used to see Convercent in my SSO.mozilla.org list as well, and that it is missing makes me feel the issue is at least partially on our side

**Comment by gene1wood** [comment]
For SSO issues like this go ahead and [open a bugzilla ticket here](https://bugzilla.mozilla.org/enter_bug.cgi?product=Infrastructure%20%26%20Operations&component=SSO%3A%20Issues)
